[input]
base_directory = "posts"
url_prefix = "/posts/"
files = [
    {path = "ssg-ssr.md", url = "ssg-ssr", title = "When to Use Static Generation v.s. Server-side Rendering"},
    {path = "pre-rendering.md", url = "pre-rendering", title = "Two Forms of Pre-rendering"},
]